server:
  port: 7002
app:
  id: apollo-client-001
apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true

spring:
  application:
    name: apollo2

apolloinfo: test


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      version: 2.0
      is-test: true
