#spring:
##  profiles: dev
#  application:
#    name: config-client
#  cloud:
#    config:
#      uri: http://127.0.0.1:8000
#      label: master
#      profile: dev
#      name: config-client


info: default

management:
  endpoints:
    web:
      exposure:
        # * 代表所有暴露所有端点，不然看不到 /actuator/refresh接口
        include: "*"