server:
  port: 15000
spring:
  application:
    name: eureka-app

app:
  id: springboot-eureka
apollo:
  meta: http://192.168.1.111:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true

eureka:
  client:
    # 是否注册到eureka
    register-with-eureka: true
    # eureka之间是否相互注册
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.104:15000/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册中心里唯一id标识
    # 是否以ip注册
    prefer-ip-address: false
    # 心跳检测时间间隔，如果在指定时间内没有收到client心跳就会被移除
    lease-expiration-duration-in-seconds: 30
    # client的心跳时间，每隔5秒向server发送心跳
    lease-renewal-interval-in-seconds: 5
  server:
    eviction-interval-timer-in-ms: 5000